#pragma once

#define MAX_CHANNELS 2000
#define DEFAULT_VOLUME 0.75f
#define MONITOR_TRACK_INTERVAL_MS 300
#define MAX_TIME_ERROR_MS 100

// graph
#define MAX_X_AXIS_VALUE 1000
#define MAX_AMPLITUDE 1
